exposureValue: 140
focusValue: 30
autofocusEnabled: 0
setAperature: 3
setAutoExposureValue: 0
brightness: 128
contrast: 128
saturation: 128
gain: 255
sharpness: 128
backlightCompensation: 0
whiteBalanceTemperature: 4000
whiteBalanceAuto: 1
onAutofocusToggleValue: 0