exposureValue: 3
focusValue: 0
autofocusEnabled: 0
setAperature: 1
setAutoExposureValue: 0
brightness: 131
contrast: 128
saturation: 128
gain: 255
sharpness: 124
backlightCompensation: 0
whiteBalanceTemperature: 4000
whiteBalanceAuto: 1