exposureValue: 521
focusValue: 0
autofocusEnabled: 0
setAperature: 0
setAutoExposureValue: 0
brightness: 106
contrast: 118
saturation: 128
gain: 156
sharpness: 128
backlightCompensation: 0
whiteBalanceTemperature: 4000
whiteBalanceAuto: 1