exposureValue: 232
focusValue: 0
autofocusEnabled: 1
setAperature: 1
setAutoExposureValue: 0
brightness: 128
contrast: 128
saturation: 128
gain: 95
sharpness: 171
backlightCompensation: 0
whiteBalanceTemperature: 3250
whiteBalanceAuto: 1

91 18