exposureValue: 212
focusValue: 30
autofocusEnabled: 0
setAperature: 1
setAutoExposureValue: 0
brightness: 124
contrast: 128
saturation: 128
gain: 129
sharpness: 150
backlightCompensation: 0
whiteBalanceTemperature: 4000
whiteBalanceAuto: 1